---
- name: Docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: Install docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Pip install docker
  pip:
    name: docker
